apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: banco-replicaset
  labels:
    app: banco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
      - name: banco-container
        image: moisesalc/banco-it_talent:latest
        ports:
        - containerPort: 3306
